import fs from 'node:fs';

const source = JSON.parse(fs.readFileSync('data/blr-source-products.json', 'utf8'));
const content = {
  DPS500: { category: 'Sensorik', type: 'Differenzdruckschalter', description: 'Für die Überwachung von Luftdruckdifferenzen in Lüftungsanlagen.', highlights: ['50–500 Pa', 'IP54'], specs: { Druckbereich: '50–500 Pa', Medium: 'Luft', Schutzart: 'IP54', Rücksetzung: 'Automatisch', 'Maximaler Druck': '10 mbar' } },
  ML7425A6008: { category: 'Ventilantriebe', type: 'Ventilantrieb mit Federrücklauf', description: 'Stetiger 600-N-Antrieb. Bei Spannungsausfall fährt die Stange aus.', highlights: ['600 N', '24 V AC'], specs: { Stellkraft: '600 N', Versorgung: '24 V AC', Ansteuerung: '0/2–10 V DC', Regelhub: '20 mm', Schutzart: 'IP54', Federrücklauf: 'Ja, Stange fährt aus', Laufzeit: '1,8 min' } },
  CLNXEHSERIES26ND: { brand: 'CentraLine by Honeywell', category: 'Steuerung & Module', type: 'EAGLEHAWK NX Anlagenregler', description: 'Niagara-basierter Controller mit 26 Ein- und Ausgängen für die Gebäudeautomation.', highlights: ['26 E/A', 'Niagara'], specs: { Serie: 'EAGLEHAWK NX', 'Ein-/Ausgänge': '26', Kommunikation: 'BACnet, LON, Modbus, M-Bus, KNX IP', Software: 'ARENA NX', Anschluss: 'Schraubklemmen' } },
  DPTE1000: { category: 'Sensorik', type: 'Differenzdrucktransmitter', description: 'Druckmessung für Luft sowie nicht brennbare, nicht aggressive Gase.', highlights: ['0–1.000/2.500 Pa', '4–20 mA'], specs: { Druckbereich: '0–1.000 / 2.500 Pa', Ausgangssignal: '4–20 mA', Versorgung: '18–30 V DC', Anschluss: '3-Leiter', Schutzart: 'IP54 mit Abdeckung', Betriebstemperatur: '0 bis 50 °C' } },
  CLIOP830A: { brand: 'CentraLine by Honeywell', category: 'Steuerung & Module', type: 'Gemischtes Panel-Bus-E/A-Modul', description: 'Ein- und Ausgangsmodul mit steckbaren Klemmen zur Montage auf der DIN-Schiene.', highlights: ['Panel-Bus', '24 V AC'], specs: { Kommunikation: 'Panel-Bus', Versorgung: '24 V AC', Montage: 'DIN-Schiene', Anschluss: 'Steckbare Klemmen', Statusanzeige: 'LED', Breite: '90 mm' } },
  'FT6961-60': { category: 'Frostschutz', type: 'Frostschutzwächter', description: 'Schutzthermostat für Luftheizungs- und Klimaanlagen mit automatischer Rücksetzung.', highlights: ['−10 bis +12 °C', '1,8 m Kapillare'], specs: { Temperaturbereich: '−10 bis +12 °C', Kapillarrohr: '1,8 m', Rücksetzung: 'Automatisch', Verwendung: 'Luftheizungs- und Klimaanlagen', Zubehör: '3 Halterungen' } },
  'N20230-SW2': { category: 'Klappenantriebe', type: 'SmartAct Klappenantrieb', description: 'Drehantrieb für Luftklappen mit Handverstellung und zwei Hilfsschaltern.', highlights: ['20 Nm', '230 V AC'], specs: { Drehmoment: '20 Nm', Versorgung: '230 V AC', Ansteuerung: '2-/3-Punkt', Schutzart: 'IP54', Laufzeit: '110 s', Hilfsschalter: '2', Handverstellung: 'Ja' } },
  ML7425B6007: { category: 'Ventilantriebe', type: 'Ventilantrieb mit Federrücklauf', description: 'Stetiger 600-N-Antrieb. Bei Spannungsausfall fährt die Stange ein.', highlights: ['600 N', '24 V AC'], specs: { Stellkraft: '600 N', Versorgung: '24 V AC', Ansteuerung: '0/2–10 V DC', Regelhub: '20 mm', Schutzart: 'IP54', Federrücklauf: 'Ja, Stange fährt ein', Laufzeit: '1,8 min' } },
  'XS821-22': { brand: 'CentraLine by Honeywell', category: 'Steuerung & Module', type: 'Klemmsockel für Analogmodule', description: 'Anschlusssockel für E/A-Module aus dem CentraLine-Sortiment.', highlights: ['Klemmsockel', 'Analogmodule'], specs: { Produkttyp: 'Klemmsockel', Anwendung: 'E/A-Module', Marke: 'CentraLine' } },
  'AF20-B65': { category: 'Sensorik', type: 'Außentemperaturfühler', description: 'Temperaturfühler für die Außenmontage mit NTC-20-kΩ-Sensorelement.', highlights: ['NTC 20 kΩ', 'IP65'], specs: { Messbereich: '−40 bis +70 °C', Sensorelement: 'NTC 20 kΩ', Schutzart: 'IP65', Montage: 'Außenwand', Maße: '82,2 × 68 × 44,5 mm' } },
  ML7421A3004: { category: 'Ventilantriebe', type: 'Stetiger Ventilantrieb', description: 'Kräftiger Antrieb mit 1.800 N, manueller Verstellung und mehreren Steuersignalen.', highlights: ['1.800 N', '20 mm Hub'], specs: { Stellkraft: '1.800 N', Versorgung: '24 V AC', Ansteuerung: '0/2–10 V DC; 0/4–20 mA', Regelhub: '20 mm', Schutzart: 'IP54', Handverstellung: 'Ja', Laufzeit: '1,9 min' } },
  ML6421A3005: { category: 'Ventilantriebe', type: '3-Punkt-Ventilantrieb', description: 'Ventilantrieb mit 1.800 N Stellkraft, 20 mm Hub und Handverstellung.', highlights: ['1.800 N', '3-Punkt'], specs: { Stellkraft: '1.800 N', Versorgung: '24 V AC', Ansteuerung: '3-Punkt', Regelhub: '20 mm', Schutzart: 'IP54', Handverstellung: 'Ja', Laufzeit: '1,9 min' } },
};
const products = source.map(p => {
  if (!content[p.name] || !p.localImage) throw new Error(`Missing content for ${p.name}`);
  return { id: p.name, brand: 'Honeywell', ...content[p.name], priceCents: Math.round(Number(p.offers.price) * 100), image: p.localImage, sourceUrl: p.sourceUrl, priceDate: p.sourceDate };
});
fs.writeFileSync('dist/shop/products.mjs', 'export const products = ' + JSON.stringify(products, null, 2) + ';\n');
console.log(`Prepared ${products.length} products from BLR24 source data.`);
